gene_name_list = c('SCEL',
                   'PORCN',
                   'MG61',
                   'PORC',
                   'PPN',
                   'FAM118B',
                   'PLSCR1',
                   'CARD19',
                   'C9orf89',
                   'ACTR3C',
                   'ARP11',
                   'PDGFC',
                   'SCDGF',
                   'UNQ174/PRO200',
                   'CEP63',
                   'NEO1',
                   'IGDCC2',
                   'NGN',
                   'EN1',
                   'COL16A1',
                   'FP1572',
                   'KIF16B',
                   'C20orf23',
                   'KIAA1590',
                   'SNX23',
                   'AAMP',
                   'TEF',
                   'KIAA1655',
                   'SLC30A6',
                   'ZNT6',
                   'SREK1',
                   'SFRS12',
                   'SRRP86',
                   'PEX1',
                   'WAPL',
                   'FOE',
                   'KIAA0261',
                   'WAPAL',
                   'SH2B1',
                   'KIAA1299',
                   'SH2B',
                   'OCRL',
                   'OCRL1',
                   'ZNF337',
                   'HLA-DMB',
                   'DMB',
                   'RING7',
                   'APEH',
                   'D3F15S2',
                   'D3S48E',
                   'DNF15S2',
                   'FBXW7',
                   'FBW7',
                   'FBX30',
                   'SEL10',
                   'MRAS',
                   'RRAS3',
                   'RHBDF2',
                   'IRHOM2',
                   'RHBDL5',
                   'RHBDL6',
                   'PARN',
                   'DAN',
                   'TMEM182',
                   'UNQ6974/PRO21957',
                   'SLC52A2',
                   'GPR172A',
                   'PAR1',
                   'RFT3',
                   'STK26',
                   'MASK',
                   'MST4',
                   'TRAF5',
                   'RNF84',
                   'MFHAS1',
                   'MASL1',
                   'HOOK1',
                   'DENR',
                   'DRP1',
                   'H14',
                   'POLM',
                   'polmu',
                   'ALG2',
                   'UNQ666/PRO1298',
                   'METTL22',
                   'C16orf68',
                   'LP8272',
                   'RRBP1',
                   'KIAA1398',
                   'LETMD1',
                   'ABI3BP',
                   'NESHBP',
                   'TARSH',
                   'LIG1',
                   'CHEK2',
                   'CDS1',
                   'CHK2',
                   'RAD53',
                   'TRIM4',
                   'RNF87',
                   'TFEC',
                   'BHLHE34',
                   'TCFEC',
                   'TFECL',
                   'ZNF571',
                   'HSPC059',
                   'PWWP3A',
                   'EXPAND1',
                   'MUM1',
                   'MRPL9',
                   'NDUFV1',
                   'UQOR1',
                   'METTL25',
                   'C12orf26',
                   'KYNU',
                   'TMEM181',
                   'GPR178',
                   'KIAA1423',
                   'ARHGEF12',
                   'KIAA0382',
                   'LARG',
                   'FGG',
                   'PRO2061',
                   'XRCC4',
                   'GGA3',
                   'KIAA0154',
                   'RNPEPL1',
                   'TROAP',
                   'MAP4',
                   'CLCN7',
                   'SART1',
                   'FNDC3B',
                   'FAD104',
                   'NS5ABP37',
                   'UNQ2421/PRO4979/PRO34274',
                   'NEK7',
                   'NIP7',
                   'CGI-37',
                   'HSPC031',
                   'HSPC180',
                   'OK/SW-cl.76',
                   'OK/SW-cl.78',
                   'PFKM',
                   'PFKX',
                   'CLINT1',
                   'ENTH',
                   'EPN4',
                   'EPNR',
                   'KIAA0171',
                   'MLIP',
                   'C6orf142',
                   'Cip',
                   'MYH10',
                   'HEPH',
                   'KIAA0698',
                   'UNQ2562/PRO6242',
                   'COL17A1',
                   'BP180',
                   'BPAG2',
                   'PHF6',
                   'CENP-31',
                   'KIAA1823',
                   'WDR5',
                   'BIG3',
                   'PLA2G4C',
                   'SENP2',
                   'KIAA1331',
                   'RASA3',
                   'HNRNPD',
                   'AUF1',
                   'HNRPD',
                   'SRSF11',
                   'SFRS11',
                   'TAPT1',
                   'CMVFR',
                   'FHIP1B',
                   'C11orf56',
                   'FAM160A2',
                   'KIAA1759',
                   'TMEM98',
                   'UNQ536/PRO1079',
                   'CSGALNACT2',
                   'CHGN2',
                   'GALNACT2',
                   'PRO0082',
                   'MTCH2',
                   'MIMP',
                   'HSPC032',
                   'PLAAT2',
                   'HRASLS2',
                   'METTL6',
                   'PIP4K2B',
                   'PIP5K2B',
                   'TCF12',
                   'BHLHB20',
                   'HEB',
                   'HTF4',
                   'HMGN5',
                   'NSBP1',
                   'ABCA12',
                   'ABC12',
                   'NFIB',
                   'SMPD4',
                   'KIAA1418',
                   'SKNY',
                   'ATL3',
                   'ABHD17A',
                   'C19orf27',
                   'FAM108A1',
                   'ZMIZ1',
                   'KIAA1224',
                   'RAI17',
                   'ZIMP10',
                   'CRTC2',
                   'TORC2',
                   'ANGPT1',
                   'KIAA0003',
                   'MORC4',
                   'ZCW4',
                   'ZCWCC2',
                   'ILRUN',
                   'C6orf106',
                   'RANBP2',
                   'NUP358',
                   'SRGN',
                   'PRG',
                   'PRG1',
                   'DUSP5',
                   'VH3',
                   'PTS',
                   'MTMR12',
                   'KIAA1682',
                   'PIP3AP',
                   'SENP6',
                   'KIAA0797',
                   'SSP1',
                   'SUSP1',
                   'FKSG6',
                   'MTAP',
                   'MSAP',
                   'GCH1',
                   'DYT5',
                   'GCH',
                   'CFB',
                   'BF',
                   'BFD',
                   'COLGALT1',
                   'GLT25D1',
                   'PSEC0241',
                   'PTK7',
                   'CCK4',
                   'EIF5B',
                   'IF2',
                   'KIAA0741',
                   'AKR7A2',
                   'AFAR',
                   'AFAR1',
                   'AKR7',
                   'SNRNP48',
                   'C6orf151',
                   'AMZ2',
                   'BM-014',
                   'IFT25',
                   'C1orf41',
                   'HSPB11',
                   'HSPC034',
                   'FBXL5',
                   'FBL4',
                   'FBL5',
                   'FLR1',
                   'SLC15A4',
                   'PHT1',
                   'PTR4',
                   'FP12591',
                   'ZNF234',
                   'ZNF269',
                   'LDLR',
                   'TMEM254',
                   'C10orf57',
                   'GGCX',
                   'GC')
gene_name_list <- c('ABAT',
                    'ACAA1',
                    'ACMSD',
                    'ACOT4',
                    'ACOT8',
                    'ACOX2',
                    'ACSF3',
                    'ACSL1',
                    'ACSM2A',
                    'ACSM3',
                    'ACYP1',
                    'ADH4',
                    'ADH5',
                    'ADH6',
                    'ADI1',
                    'ALAD',
                    'ALDH1B1',
                    'ALDH6A1',
                    'ALDH8A1',
                    'ALDOB',
                    'APIP',
                    'ASPDH',
                    'AUH',
                    'BAX',
                    'BCKDHB',
                    'BDH1',
                    'BHMT',
                    'BHMT2',
                    'CAT',
                    'CBR4',
                    'CDO1',
                    'CLK1',
                    'CNDP1',
                    'CRYAA',
                    'DHRS4',
                    'DLD',
                    'DMGDH',
                    'DPYS',
                    'ECHS1',
                    'ENO3',
                    'EPHX2',
                    'FAH',
                    'FBP1',
                    'FBXO2',
                    'FMO5',
                    'FTCD',
                    'GCDH',
                    'GCH1',
                    'GFUS',
                    'GOT1',
                    'GOT2',
                    'GPT',
                    'GPT2',
                    'GRHPR',
                    'GSTZ1',
                    'HAAO',
                    'HADH',
                    'HADHA',
                    'HAO2',
                    'HGD',
                    'HIBADH',
                    'HMGCL',
                    'HMGCS2',
                    'HPD',
                    'HSD17B10',
                    'HSD17B12',
                    'HSD17B8',
                    'IVD',
                    'KHK',
                    'LDHD',
                    'LOC102724652',
                    'MAN1C1',
                    'MCEE',
                    'MMUT',
                    'MOCS2',
                    'NFKBIA',
                    'NUDT7',
                    'OAT',
                    'OGDHL',
                    'OXSM',
                    'PANK1',
                    'PC',
                    'PCCA',
                    'PCCB',
                    'PDIA4',
                    'PEX11G',
                    'PGM1',
                    'PHYH',
                    'PRODH2',
                    'PSMB5',
                    'PSMB6',
                    'PSMD13',
                    'PXMP2',
                    'RAB1A',
                    'SAR1B',
                    'SARDH',
                    'SAT2',
                    'SDHB',
                    'SEC24B',
                    'SEM1',
                    'SHMT1',
                    'SORD',
                    'SSR4',
                    'SUCLA2',
                    'SUCLG1',
                    'SUCLG2',
                    'TKFC')
gene_name_list <- c('ABI1',
                     'ACTN1',
                     'ADPRHL1',
                     'ADTRP',
                     'AGPAT1',
                     'ANGPT4',
                     'ASXL3',
                     'ATP5F1C',
                     'ATP5F1C',
                     'ATP5ME',
                     'BBS9',
                     'BCHE',
                     'BMPER',
                     'BRI3',
                     'C10orf67',
                     'C2CD5',
                     'C2CD5',
                     'CD36',
                     'CEACAM1',
                     'CEACAM1',
                     'CENPX',
                     'CHRNA4',
                     'CIDEA',
                     'CLDN2',
                     'CLK1',
                     'CLK1',
                     'CLK4',
                     'CLU',
                     'COMMD5',
                     'CRYBG2',
                     'CRYL1',
                     'CTNNA3',
                     'DAB1',
                     'DAND5',
                     'DBI',
                     'DCHS2',
                     'DGUOK',
                     'DMD',
                     'DMKN',
                     'DMRTA2',
                     'DUT',
                     'DUT',
                     'EGFLAM',
                     'EGFLAM',
                     'EPHA7',
                     'EXOC6',
                     'FABP6',
                     'FAM178B',
                     'FAM180B',
                     'FATE1',
                     'FXR1',
                     'GPM6A',
                     'GPR19',
                     'GRIK3',
                     'GSTZ1',
                     'GSTZ1',
                     'HSPB11',
                     'IBSP',
                     'IL20RB',
                     'INA',
                     'IP6K2',
                     'ITGA7',
                     'ITLN2',
                     'KCNA4',
                     'KCNH7',
                     'KCNN2',
                     'KCNT2',
                     'KHK',
                     'KIAA1217',
                     'KRT24',
                     'LAS1L',
                     'LCN12',
                     'LMAN2L',
                     'LOXL1',
                     'LRAT',
                     'LSP1',
                     'LTB',
                     'LYPD3',
                     'MAGED2',
                     'MAP1LC3C',
                     'MAPKAP1',
                     'MAPT',
                     'MARVELD2',
                     'MOB2',
                     'MORF4L2',
                     'MORN5',
                     'MPPED1',
                     'MPZ',
                     'MRO',
                     'MT1F',
                     'MYO16',
                     'NAALAD2',
                     'NABP2',
                     'NLGN1',
                     'NLN',
                     'NNAT',
                     'NTHL1',
                     'NTHL1',
                     'NTRK3',
                     'NUF2',
                     'NXPH2',
                     'ORC1',
                     'OTOGL',
                     'OTUB2',
                     'PAGE5',
                     'PCBD1',
                     'PCCA',
                     'PCSK2',
                     'PGAP2',
                     'PKIG',
                     'PKIG',
                     'PKIG',
                     'PLA2G2C',
                     'PLSCR1',
                     'PMM2',
                     'PMP2',
                     'PMP22',
                     'PMP22',
                     'POU3F4',
                     'PSD3',
                     'PTMA',
                     'PTPRQ',
                     'PTPRS',
                     'RAB23',
                     'RARB',
                     'RBP4',
                     'RBP4',
                     'RHBDD2',
                     'RNH1',
                     'RTN4',
                     'RTN4',
                     'RXRG',
                     'SALL3',
                     'SERPINC1',
                     'SH3GL3',
                     'SIM2',
                     'SIM2',
                     'SINHCAF',
                     'SINHCAF',
                     'SLC14A2',
                     'SLC23A2',
                     'SLC5A1',
                     'SLC5A9',
                     'SMAD7',
                     'SMCO4',
                     'SMCO4',
                     'SNCA',
                     'SPX',
                     'ST8SIA1',
                     'STRA6',
                     'SULT4A1',
                     'SUN3',
                     'SYN2',
                     'SYT4',
                     'TAMM41',
                     'TCEAL8',
                     'TCEAL8',
                     'TEKT3',
                     'TM2D1',
                     'TM2D1',
                     'TNFAIP8L3',
                     'TNFAIP8L3',
                     'TPM1',
                     'TPO',
                     'TSPAN2',
                     'TTC9B',
                     'TYRO3',
                     'UBE2QL1',
                     'WNT3')
gene_name_list <- c('ENSG00000125995',
                    'ENSG00000111057',
                    'ENSG00000135245',
                    'ENSG00000044574',
                    'ENSG00000275214',
                    'ENSG00000165949',
                    'ENSG00000163041',
                    'ENSG00000117450',
                    'ENSG00000163191',
                    'ENSG00000108821',
                    'ENSG00000102265',
                    'ENSG00000090382',
                    'ENSG00000196262',
                    'ENSG00000084207',
                    'ENSG00000111640',
                    'ENSG00000164266')
gene_name_list <- c('ENSG00000211445',
                    'ENSG00000122852',
                    'ENSG00000163586',
                    'ENSG00000244734',
                    'ENSG00000188536',
                    'ENSG00000125148',
                    'ENSG00000170323',
                    'ENSG00000163017',
                    'ENSG00000110169',
                    'ENSG00000206172',
                    'ENSG00000011465',
                    'ENSG00000107796',
                    'ENSG00000100316',
                    'ENSG00000171560',
                    'ENSG00000205358',
                    'ENSG00000196616',
                    'ENSG00000132465',
                    'ENSG00000198417')
gene_name_list <- c('ENSG00000116194',
                    'ENSG00000168497',
                    'ENSG00000266964',
                    'ENSG00000129596',
                    'ENSG00000182916',
                    'ENSG00000114200',
                    'ENSG00000140092',
                    'ENSG00000104332',
                    'ENSG00000069702',
                    'ENSG00000111404',
                    'ENSG00000127241',
                    'ENSG00000163687',
                    'ENSG00000170271',
                    'ENSG00000180879',
                    'ENSG00000186198',
                    'ENSG00000187699',
                    'ENSG00000287542',
                    'ENSG00000133169',
                    'ENSG00000197165') ##shared_down_regulated_genes
gene_name_list <- c('ENSG00000000419',
                     'ENSG00000008018',
                     'ENSG00000053372',
                     'ENSG00000063177',
                     'ENSG00000077152',
                     'ENSG00000079462',
                     'ENSG00000094804',
                     'ENSG00000100575',
                     'ENSG00000102554',
                     'ENSG00000105202',
                     'ENSG00000112312',
                     'ENSG00000114391',
                     'ENSG00000117632',
                     'ENSG00000119640',
                     'ENSG00000123975',
                     'ENSG00000127922',
                     'ENSG00000132646',
                     'ENSG00000136518',
                     'ENSG00000136942',
                     'ENSG00000142856',
                     'ENSG00000144034',
                     'ENSG00000147669',
                     'ENSG00000151725',
                     'ENSG00000156697',
                     'ENSG00000159055',
                     'ENSG00000159596',
                     'ENSG00000162642',
                     'ENSG00000163807',
                     'ENSG00000163918',
                     'ENSG00000164104',
                     'ENSG00000171311',
                     'ENSG00000198918',
                     'ENSG00000203760',
                     'ENSG00000223573',
                     'ENSG00000233795',
                     'ENSG00000236808',
                     'ENSG00000273780',
                     'ENSG00000276368',
                     'ENSG00000280548') #magoh high correlation genes

library('clusterProfiler') 
library('org.Hs.eg.db')
library(stringr)
library(ggplot2)
library(dplyr)
library(ggrepel)
library("ggsci")
library(svglite)
library("enrichplot")
tis = 'tumor_spec_gene'
tis = 'ir_sig_up'
tis = 'tumor_>_normal'
tis = 'tumor_<_normal'
tis = 'liv_kid_share'
tis = 'down_reg_shared'
tis = 'magoh'

gene_name_list <- read.table('/data1/DYY/data/ir_sig_deg_barplot/up_gene.txt')

gene_name_list <- read.table('/data1/DYY/data/all_tumor_spec_gene.txt')
gene_name_list <- read.table('/data1/DYY/bambu/ir_sig_up_gene.csv')
gene_name_list <- read.table('/data1/DYY/bambu/tumor_specific_gene_in_2_tissues.csv',header = F)
gene_name_list <- read.table('/data1/DYY/bambu/all_ts_gene.csv')
head(gene_name_list)
ENTREZID<- bitr(gene_name_list$V1, fromType = "ENSEMBL", toType=c("SYMBOL","ENTREZID"),OrgDb = org.Hs.eg.db)
ego_BP <- enrichGO(gene = ENTREZID$ENTREZID, #universe = names(geneList),
                   OrgDb = org.Hs.eg.db,ont = "BP", pAdjustMethod = "BH",pvalueCutoff = 0.5,qvalueCutoff = 0.5,readable = TRUE)
write.table(ego_BP,paste('~/bambu_data_kegg_go/',tis,'_go_bp.csv',sep = ''), sep = '\t', quote = FALSE, row.names = FALSE)
# test <- read.table(paste('~/tmp_data_kegg_go/',tis,'_go_bp.csv',sep = ''), sep = '\t')
plotpath <- '/data1/DYY/bambu/plot/enrichment_plot/'
kegg <- enrichKEGG(
  gene = ENTREZID$ENTREZID,  #基因列表文件中的基因名称
  keyType = 'kegg',  #KEGG 富集
  organism = 'human',  
  pAdjustMethod = 'fdr',  #指定 p 值校正方法
  pvalueCutoff = 0.5,  #指定 p 值阈值（可指定 1 以输出全部）
  qvalueCutoff = 0.5)  #指定 q 值阈值（可指定 1 以输出全部）
if (length(kegg)!=0) {
  kegg <- setReadable(kegg, OrgDb = org.Hs.eg.db, keyType="ENTREZID")

  write.table(kegg,paste('~/bambu_data_kegg_go/',tis,'_kegg.csv',sep = ''), sep = '\t', quote = FALSE, row.names = FALSE)
  KEGG_dataset <- read.table(file = paste('~/bambu_data_kegg_go/',tis,'_kegg.csv',sep = ''),header = TRUE, sep = "\t")
  ##对kegg数据进行按照p值排序
  KEGG_dataset <- arrange(KEGG_dataset,KEGG_dataset[,5])
  KEGG_dataset$enrichment_fold <- apply(KEGG_dataset,1,function(x){
    GeneRatio=eval(parse(text=x["GeneRatio"]))
    BgRatio=eval(parse(text=x["BgRatio"]))
    enrichment_fold=round(GeneRatio/BgRatio,2)
    enrichment_fold
  })
  #Pathway列最好转化成因子型，否则作图时ggplot2会将所有Pathway按字母顺序重排序
  #将Pathway列转化为因子型
  KEGG_dataset$Description <- factor(KEGG_dataset$Description,levels = rev(KEGG_dataset$Description))
  mytheme <- theme(axis.title=element_text(size=14,colour = 'black'), #坐标轴标题
                   axis.text=element_text(size=14,colour = 'black'), #坐标轴标签
                   axis.line = element_line(linewidth = 0.5, colour = 'black'), #轴线
                   panel.background = element_rect(color='black'), #绘图区边框
                   legend.key = element_blank() #关闭图例边框
  )
  p <- ggplot(head(KEGG_dataset[order(KEGG_dataset$enrichment_fold, decreasing = TRUE), ],10),aes(x=enrichment_fold,y=Description,colour=-1*log10(p.adjust),size=Count))+
    geom_point()+
    scale_size(range=c(2, 10))+
    # scale_colour_gradient(low = "#6d8fbf", high = "#e4e4ea")+
    # scale_colour_gradient(low = "#843F0B", high = "#EE822F")+
    scale_fill_gradient(low = "#4399ab", high = "#e5eca2")+
    theme_bw()+
    ylab("KEGG Pathway Terms")+
    xlab("Enrichment fold")+
    labs(color=expression(-log[10](PValue)))+
    theme(legend.title=element_text(size=14), legend.text = element_text(size=14))+
    theme(axis.title.y = element_text(margin = margin(r = 50)),axis.title.x = element_text(margin = margin(t = 20)))+
    theme(axis.text.x = element_text(face ="bold",color="black",angle=0,vjust=1))
  kegg_plot <- p+mytheme
  kegg_plot
  kegg_plottitle <- paste(tis,"_kegg_dotq_0.1",sep = '_')
  ggsave(paste(plotpath,kegg_plottitle,'.pdf',sep = ''),width = 10, height = 10,plot = go_plot)
}

###############
#####go_bp#####
###############
go_bp = read.table(paste('~/bambu_data_kegg_go/',tis,'_go_bp.csv',sep = ''), sep = '\t',header = T)
go_bp$enrichment_fold <- apply(go_bp,1,function(x){
  GeneRatio=eval(parse(text=x["GeneRatio"]))
  BgRatio=eval(parse(text=x["BgRatio"]))
  enrichment_fold=round(GeneRatio/BgRatio,2)
  enrichment_fold
})
##对go数据进行按照p值排序
go_bp <- arrange(go_bp,go_bp[,10])
#Pathway列最好转化成因子型，否则作图时ggplot2会将所有Pathway按字母顺序重排序
#将Pathway列转化为因子型
go_bp$Description <- factor(go_bp$Description,levels = rev(go_bp$Description))
p <- ggplot(go_bp[1:10,],aes(y=as.numeric(enrichment_fold),x=Description,fill=-1*log10(p.adjust))) + 
  geom_bar(stat="identity",position = "dodge") +
  # facet_grid(Category~.,scales = "free",space = "free") + 
  coord_flip() + 
  theme_bw() + 
  scale_fill_gradient(low = "#4399ab", high = "#e5eca2")+
  # scale_fill_gradient(low = "#843F0B", high = "#EE822F")+
  # scale_color_gsea()+
  theme(plot.title = element_text(hjust = 0.5),
        strip.text.y = element_text(size = 14),
        legend.position="right",
        legend.title = element_text(size=18),
        legend.text = element_text(size=14),
        # axis.text.x = element_text(size=14),
        axis.text.y = element_text(size=14),
        # axis.title.x = element_text(size=14),
        axis.title.y = element_text(size=14))
go_plot <- p  #+ scale_x_discrete(labels=function(x) str_wrap(x, width=10))
go_plot
#对y轴标签分行
# p + scale_x_discrete(labels=function(x) str_wrap(x, width=10))
# unlink(file.path('~/tmp_data_kegg_go/', '*'), recursive = TRUE)
# go_plottitle <- paste(tis,"_go_bp_plot",sep = '_')
# mf_title <- paste(tis,"EnrichmentGO_MF_dot",sep = '_')
# cc_title <- paste(tis,"EnrichmentGO_CC_dot",sep = '_')
bp_title <- paste(tis,"EnrichmentGO_BPplot",sep = '_')
# mf <- dotplot(ego_MF,title=mf_title)
# cc <- dotplot(ego_CC,title=cc_title)
# bp <- dotplot(ego_BP,title=bp_title)
# ggsave(paste(plotpath,mf_title,'.pdf',sep = ''), plot = mf)
# ggsave(paste(plotpath,cc_title,'.pdf',sep = ''), plot = cc)
ggsave(paste(plotpath,bp_title,'.pdf',sep = ''),width = 10, height = 10, plot = go_plot)

